version: '3'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - "8080:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=nextcloud
      - SQLITE_DB_DIR=/var/www/html/data
    volumes:
      - nextcloud_data:/var/www/html

  locust:
    image: locustio/locust
    container_name: locust
    command: -f /locust/tasks.py --host=http://nextcloud
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/locust
      - ./test-data:/test-data
    
volumes:
  nextcloud_data:
